version: "3.9"
services:
  certbot:
    image: 'certbot/certbot'
    depends_on:
      ingress:
        condition: service_started
    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - nginx-static-data:/var/www/html
    command: certonly --webroot --webroot-path /var/www/html --email nikmoroz2002@yandex.ru --agree-tos --no-eff-email  -d it-profession.fbtw.ru
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - /it_profession/.env
  full_db:
    container_name: full_db
    image: postgres:13.12
    ports:
      - "5432:5432"
    env_file:
      - /it_profession/.env
    volumes:
      - './target/postgres-data:/var/lib/postgresql/data'
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    deploy:
      resources:
        limits:
          memory: "1500M"
        reservations:
          cpus: "0.25"
          memory: "128M"
  ingress:
    image: 'it-profession-ingress:1.0'
    build: ./ingress/
    ports:
      - '80:80'
      - '443:443'
    container_name: it-profession-ingress
    volumes:
      - letsencrypt-data:/etc/letsencrypt
      - nginx-static-data:/var/www/html
volumes:
  letsencrypt-data:
  nginx-static-data: