# Generated by Django 3.2.5 on 2023-10-27 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geozones', '0004_deprecatedgeozonemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satellites', '0004_auto_20231027_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_price', models.FloatField()),
                ('per_photo', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('picture', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('geozone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geozones.geozonemodel')),
                ('satellites', models.ManyToManyField(to='satellites.SatelliteModel')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tarifmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
