# Generated by Django 3.2.5 on 2023-10-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Data collected'), (2, 'Done')], default=0),
        ),
    ]
