# Generated by Django 3.2.5 on 2023-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginmodel',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
