# Generated by Django 3.2.5 on 2023-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=256, null=True, upload_to='pictures/')),
                ('link', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
