# Generated by Django 3.2.5 on 2023-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='url',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='pictures/uploaded/'),
        ),
    ]
