# Generated by Django 3.2.5 on 2023-10-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_ordermodel_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pay_method', models.CharField(choices=[('sber', 'Sber'), ('alpha', 'Alpha'), ('doly', 'Dolyame'), ('ukassa', 'Ukassa'), ('cloudPay', 'Cloud'), ('payPal', 'Paypal'), ('test', 'Test')], max_length=255)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Register'), (1, 'Hold'), (2, 'Paid'), (3, 'Cancel'), (4, 'Refund'), (5, 'Auth'), (6, 'Bad Auth'), (10, 'Wait Commit'), (11, 'Commited'), (20, 'Rejected')])),
                ('bank_order_uid', models.CharField(max_length=255)),
                ('bank_order_id', models.CharField(max_length=255)),
                ('status_changed_at', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='orders.ordermodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderpaymodel',
            index=models.Index(fields=['bank_order_uid'], name='payments_or_bank_or_25b8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpaymodel',
            index=models.Index(fields=['bank_order_id'], name='payments_or_bank_or_613b52_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpaymodel',
            index=models.Index(fields=['order'], name='payments_or_order_i_62d643_idx'),
        ),
    ]
