# Generated by Django 3.2.5 on 2023-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bject_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=20)),
                ('epoch', models.DateTimeField()),
                ('mean_motion', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('inclination', models.FloatField()),
                ('ra_of_asc_node', models.FloatField()),
                ('arg_of_pericenter', models.FloatField()),
                ('mean_anomaly', models.FloatField()),
                ('ephemeris_type', models.IntegerField()),
                ('classification_type', models.CharField(max_length=1)),
                ('norad_cat_id', models.IntegerField()),
                ('element_set_no', models.IntegerField()),
                ('rev_at_epoch', models.IntegerField()),
                ('bstar', models.FloatField()),
                ('mean_motion_dot', models.FloatField()),
                ('mean_motion_ddot', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('resolution', models.FloatField()),
            ],
        ),
    ]
