# Generated by Django 3.2.5 on 2023-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0002_positionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellitemodel',
            old_name='bject_name',
            new_name='object_name',
        ),
        migrations.AddField(
            model_name='satellitemodel',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
