# Generated by Django 3.2.5 on 2023-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0003_auto_20231026_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellitemodel',
            name='element_set_no',
        ),
        migrations.RemoveField(
            model_name='satellitemodel',
            name='norad_cat_id',
        ),
        migrations.AddField(
            model_name='satellitemodel',
            name='element_number',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='satellitemodel',
            name='int_design',
            field=models.CharField(default='', max_length=8, verbose_name='International Designator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellitemodel',
            name='norad_id',
            field=models.IntegerField(default=1, verbose_name='Id in NORAD database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satellitemodel',
            name='arg_of_pericenter',
            field=models.FloatField(verbose_name='Argument of Perigee'),
        ),
        migrations.AlterField(
            model_name='satellitemodel',
            name='bstar',
            field=models.FloatField(verbose_name='Bstar coefficient'),
        ),
        migrations.AlterField(
            model_name='satellitemodel',
            name='classification_type',
            field=models.CharField(choices=[('U', 'Unclassified'), ('S', 'Secret'), ('C', 'Classified')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='satellitemodel',
            name='ephemeris_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='satellitemodel',
            name='ra_of_asc_node',
            field=models.FloatField(verbose_name='Right Ascension of the Ascending Node'),
        ),
    ]
