# Generated by Django 3.2.5 on 2023-10-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0005_positionmodel_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionmodel',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
