# Generated by Django 3.2.5 on 2023-10-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('geozones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geozonemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.users'),
        ),
    ]
