# Generated by Django 3.2.5 on 2023-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geozones', '0003_alter_geozonemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeprecatedGeozoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
