# Generated by Django 3.2.5 on 2023-10-27 11:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geozones', '0004_deprecatedgeozonemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deprecatedgeozonemodel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geozonemodel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
